INSERT INTO PET_TYPES (NAME) VALUES ('cat');
INSERT INTO PET_TYPES (NAME) VALUES ('dog');
INSERT INTO PET_TYPES (NAME) VALUES ('lizard');
INSERT INTO PET_TYPES (NAME) VALUES ('snake');
INSERT INTO PET_TYPES (NAME) VALUES ('bird');
INSERT INTO PET_TYPES (NAME) VALUES ('hamster');

INSERT INTO SPECIALITIES (NAME) VALUES ('radiology');
INSERT INTO SPECIALITIES (NAME) VALUES ('surgery');
INSERT INTO SPECIALITIES (NAME) VALUES ('dentistry');

INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('James', 'Carter');
INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('Helen', 'Leary');
INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('Linda', 'Douglas');
INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('Rafael', 'Ortega');
INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('Henry', 'Stevens');
INSERT INTO VETS (FIRST_NAME, LAST_NAME) VALUES ('Sharon', 'Jenkins');

INSERT INTO VET_SPECIALITIES (VET_ID, SPECIALITY_ID)
SELECT v.ID, s.ID FROM VETS v, SPECIALITIES s WHERE v.LAST_NAME = 'Leary' AND s.NAME = 'radiology';
INSERT INTO VET_SPECIALITIES (VET_ID, SPECIALITY_ID)
SELECT v.ID, s.ID FROM VETS v, SPECIALITIES s WHERE v.LAST_NAME = 'Douglas' AND s.NAME = 'surgery';
INSERT INTO VET_SPECIALITIES (VET_ID, SPECIALITY_ID)
SELECT v.ID, s.ID FROM VETS v, SPECIALITIES s WHERE v.LAST_NAME = 'Douglas' AND s.NAME = 'dentistry';
INSERT INTO VET_SPECIALITIES (VET_ID, SPECIALITY_ID)
SELECT v.ID, s.ID FROM VETS v, SPECIALITIES s WHERE v.LAST_NAME = 'Ortega' AND s.NAME = 'surgery';
INSERT INTO VET_SPECIALITIES (VET_ID, SPECIALITY_ID)
SELECT v.ID, s.ID FROM VETS v, SPECIALITIES s WHERE v.LAST_NAME = 'Stevens' AND s.NAME = 'radiology';

INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE) VALUES ('Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Leo', DATE '2010-09-07', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'cat' AND o.LAST_NAME = 'Franklin';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Basil', DATE '2012-08-06', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'hamster' AND o.FIRST_NAME = 'Betty';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Jewel', DATE '2010-03-07', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'dog' AND o.FIRST_NAME = 'Eduardo';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Rosy', DATE '2011-03-07', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'dog' AND o.FIRST_NAME = 'Eduardo';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Iggy', DATE '2010-11-30', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'lizard' AND o.FIRST_NAME = 'Harold';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'George', DATE '2010-01-20', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'snake' AND o.FIRST_NAME = 'Peter';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Samantha', DATE '2012-09-04', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'cat' AND o.FIRST_NAME = 'Jean';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Max', DATE '2012-09-04', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'cat' AND o.FIRST_NAME = 'Jean';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Lucky', DATE '2011-08-06', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'bird' AND o.FIRST_NAME = 'Jeff';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Mulligan', DATE '2007-01-20', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'dog' AND o.FIRST_NAME = 'Maria';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Freddy', DATE '2010-01-20', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'bird' AND o.FIRST_NAME = 'David';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Lucky', DATE '2010-01-20', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'dog' AND o.FIRST_NAME = 'Carlos';
INSERT INTO PETS (NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
SELECT 'Sly', DATE '2012-09-04', t.ID, o.ID FROM PET_TYPES t, OWNERS o WHERE t.NAME = 'cat' AND o.FIRST_NAME = 'Carlos';

INSERT INTO VISITS (VISIT_DATE, DESCRIPTION, PET_ID)
SELECT DATE '2013-01-01', 'rabies shot', p.ID FROM PETS p JOIN OWNERS o ON o.ID = p.OWNER_ID WHERE p.NAME = 'Samantha' AND o.FIRST_NAME = 'Jean';
INSERT INTO VISITS (VISIT_DATE, DESCRIPTION, PET_ID)
SELECT DATE '2013-01-04', 'neutered', p.ID FROM PETS p JOIN OWNERS o ON o.ID = p.OWNER_ID WHERE p.NAME = 'Samantha' AND o.FIRST_NAME = 'Jean';
INSERT INTO VISITS (VISIT_DATE, DESCRIPTION, PET_ID)
SELECT DATE '2013-01-02', 'rabies shot', p.ID FROM PETS p JOIN OWNERS o ON o.ID = p.OWNER_ID WHERE p.NAME = 'Max' AND o.FIRST_NAME = 'Jean';
INSERT INTO VISITS (VISIT_DATE, DESCRIPTION, PET_ID)
SELECT DATE '2013-01-03', 'neutered', p.ID FROM PETS p JOIN OWNERS o ON o.ID = p.OWNER_ID WHERE p.NAME = 'Max' AND o.FIRST_NAME = 'Jean';
