DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM PET_TYPES;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE PET_TYPES_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM SPECIALITIES;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SPECIALITIES_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM OWNERS;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE OWNERS_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM PETS;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE PETS_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM VISITS;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VISITS_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM VETS;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VETS_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';

    SELECT NVL(MAX(ID), 0) + 1 INTO v_start FROM VET_SPECIALITIES;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VET_SPECIALITIES_SEQ START WITH ' || v_start || ' INCREMENT BY 1 CACHE 100 NOCYCLE';
END;
/
