#:schema ../__pyronaut__/schemas/micronaut-application.schema.json

[micronaut.application]
name = 'pyronaut-petclinic'

[micronaut.banner]
enabled = false

[micronaut.server]
context-path = '${PETCLINIC_BASE_PATH:}'

[micronaut.executors.blocking]
type = 'CACHED'
virtual = false

[micronaut.views.jinja]
default-extension = '.jinja'

[micronaut.views]
folder = '.'

[micronaut.router.static-resources.default]
enabled = true
mapping = '/resources/**'
paths = ['file:static']

[micronaut.caches.vets]
expire-after-write = '60s'
maximum-size = 100

[datasources.default]
db-type = 'oracle'
url = 'jdbc:oracle:thin:@${DATABASE_URL:${ORACLE_DB_URL:}}'
create-connection-in-borrow-thread = true
schema-generate = 'NONE'
dialect = 'ORACLE'

[datasources.default.data-source-properties]
"oracle.jdbc.tokenAuthentication" = '${OCI_TOKEN:OCI_TOKEN}'
"oracle.jdbc.tokenLocation" = '${ORACLE_DB_TOKEN_DIR:}'

[flyway.datasources.default]
enabled = true
locations = ['filesystem:config/db/migration']

[ucp-manager]
enabled = false

[logger.levels]
petclinic = 'INFO'
io.micronaut.data.query = 'ERROR'
